// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3-3YP_j02yGCqB_mgxoM0WZ74fRbq2rs',
    appId: '1:517261145333:web:22860fb70888b3da3c41bc',
    messagingSenderId: '517261145333',
    projectId: 'personal-automation-engine',
    authDomain: 'personal-automation-engine.firebaseapp.com',
    databaseURL: 'https://personal-automation-engine-default-rtdb.firebaseio.com',
    storageBucket: 'personal-automation-engine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_hMaYweDWPpvxLtM22dNxeN5tPswi_g',
    appId: '1:517261145333:android:a992187fafb830fd3c41bc',
    messagingSenderId: '517261145333',
    projectId: 'personal-automation-engine',
    databaseURL: 'https://personal-automation-engine-default-rtdb.firebaseio.com',
    storageBucket: 'personal-automation-engine.firebasestorage.app',
  );
}
